FROM node:18.13 AS build-stage
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build-stage /app/dist/frontend/ /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./src/assets/env.template.js /usr/share/nginx/html/browser/assets/env.template.js
CMD ["/bin/sh", "-c", "envsubst < /usr/share/nginx/html/browser/assets/env.template.js > /usr/share/nginx/html/browser/assets/env.js && nginx -g 'daemon off;'"]